# .streamlit/secrets.toml (example)
ADMIN_EMAIL = "madhav.janumula@woxsen.edu.in"
SECURITY_EMAIL = "madhav.janumula@woxsen.edu.in"
PUBLIC_BASE_URL = "http://10.106.20.179:8501"

# SMTP 
SMTP_HOST = "smtp.office365.com"
SMTP_PORT = "587"
SMTP_SECURITY = "starttls"
SMTP_USER = "bbaweekdayoutgatepermission@woxsen.edu.in"
SMTP_PASS = "Bbaoutgate@2024"
SMTP_FROM = "bbaweekdayoutgatepermission@woxsen.edu.in"


SMTP_HOST_OVERRIDE_IP = "52.98.59.18"